title: 伝える
author: Robert Kuska
subtitle: I think my head is burning

url: "https://robert.kuska.xyz"
baseurl: ""

footer_only_homepage: true
#footer_url: "https://github.com/rhl-bthr"
#footer_text: "Theme by rhl-bthr"

profile-picture: assets/profile.png
favicon_location: assets/favicon.ico

permalink: /blog/:year-:month-:day-:title/
sass:
    style: compressed
    sass_dir: css

exclude:
 - AGENTS.md
 - .DS_Store
 - about.md
 - _archive

navbar:
 - name: "伝える"
   link: "/blog/"
 #- name: "Resume"
   #absolute-link: "https://rahulbothra.com/cv.pdf"
